# First do the source builds
@INCLUDE Dockerfile.target.sdist

# This defines the dstribution base layer
# Put only the bare minimum of common commands here, without dev tools
FROM oraclelinux:8 AS dist-base

ARG BUILDER_CACHE_BUSTER=
RUN dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --set-enabled ol8_codeready_builder && \
    dnf install -y epel-release

# Do the actual rpm build
@INCLUDE Dockerfile.rpmbuild
